import { Box, Button, Center, Container, Heading, Text } from '@chakra-ui/react';
import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container sx={{ minHeight: '100vh' }} p={'4'} display={'flex'}>
        <Center m={'auto'} flexDirection={'column'} w={'96'} gap={'4'}>
          <Heading pb={'6'}>BanhTheCake Kanban</Heading>
          <Button as={Link} href={'/login'} w={'full'}>Login</Button>
          <Button as={Link} href={'/register'} w={'full'}>Register</Button>
        </Center>
        <Box
          position={'fixed'}
          bottom={'0.5'}
          right={'0.5'}
          m={'4'}
          display={'flex'}
          gap={'1'}
          fontWeight={'semibold'}
        >
          Do you like <Text color={'yellow.300'}>potato</Text> or{' '}
          <Text color={'red.400'}>tomato</Text> ?
        </Box>
      </Container>
    </>
  );
}
